FROM nvcr.io/nvidia/pytorch:24.04-py3

ENV TZ=Europe/Istanbul
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y tzdata

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    python3 \
    python3-pip \
    git

RUN pip3 install cmake --upgrade
WORKDIR /workspace

ENV CUDNN_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDNN_DIR/lib64:$LD_LIBRARY_PATH

ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

RUN apt-get install libgtk* libspdlog-dev libfmt-dev libboost-dev ffmpeg libavformat-dev libavcodec-dev libswscale-dev pybind11-dev libxcb-xinerama0 \
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xfixes0 libxcb-cursor0 libxkbcommon-x11-0 libgl1-mesa-glx \
    libglib2.0-0 libdbus-1-3 -y && rm -rf /var/lib/apt/lists/* 


RUN pip3 install torch torchvision --upgrade --force-reinstall

RUN apt-get update && apt-get upgrade -y
RUN pip3 install onnxslim onnxruntime-gpu matplotlib tqdm requests psutil PyQt5
RUN pip3 install "numpy<2"